all: Out.txt
	cat Out.txt

Out.txt: main.exe
	mono main.exe > Out.txt

main.exe: main.cs cmath.dll
	mcs -target:exe -reference:cmath.dll -oumain.exe main.cs

CMATHDIR = C:\Users\soere\sballing\Exercises\complex
cmath.dll : $(CMATHDIR)/cmath.cs $(CMATHDIR)/complex.cs
	mcs -target:library -out:./cmath.dll $^ # note "./" in front of cmath.dll

clean:
	rm -f Out.txt main.exe cmath.dll
