all: Out.txt
	cat Out.txt

Out.txt: main.exe
	mono $< > $@

main.exe: main.cs using System;
using static System.Console;
	mcs $< -target:exe -out:main.exe -reference:passfunctions.dll

passfunctions.dll: passfunctions.cs
	mcs $< -target:library -out:passfunctions.dll

clean:
	rm -r *.exe *.dll [Ou]ut.txt
